language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
script:
- grunt deploy
branches:
  only:
  - master
notifications:
  email:
  - bartvanderschoor@gmail.com
env:
  global:
    secure: kp+wTYmwjllbbRfmDGOE7NbgAAouMjYJWDoTqFPVR74H01aViBKZeX19nhtgdYu6rL/XIR5dNf4Lm36O+rstOGKY9NYv0H0qWI0XbMXaV67nmqQ5gbEHsV3coAGiAp+xoKTwpw2xsgeu49XFVxS2mu31NstdBNxQ2IWxLSgCeAQ=
